/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BukuControl;
import Model.DataLogin;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author L E N O V O
 */
public class BukuPage extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    BukuControl bc;

    public BukuPage() {
        super("Sistem Manajemen Perpustakaan");
        initComponents();
        bc = new BukuControl(this);
        namaUser.setText("Welcome, " + DataLogin.getNama_lengkap() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        namaUser = new javax.swing.JLabel();
        navLogout = new javax.swing.JButton();
        navPengurus = new javax.swing.JButton();
        navHistory = new javax.swing.JButton();
        navBuku = new javax.swing.JButton();
        navSirkulasi = new javax.swing.JButton();
        navBeranda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CariBuku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataBuku = new javax.swing.JTable();
        searchBy = new javax.swing.JComboBox<>();
        btnCariBuku = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TampilBuku = new javax.swing.JButton();
        InputKode = new javax.swing.JTextField();
        InputJudul = new javax.swing.JTextField();
        InputPenulis = new javax.swing.JTextField();
        InputPenerbit = new javax.swing.JTextField();
        InputGenre = new javax.swing.JTextField();
        InputISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnClearForm = new javax.swing.JButton();
        btnTambahBuku = new javax.swing.JButton();
        btnUpdateBuku = new javax.swing.JButton();
        btnDeleteBuku = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 140));

        namaUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namaUser.setForeground(new java.awt.Color(255, 255, 255));
        namaUser.setText("Welcome, Nama Lengkap");

        navLogout.setBackground(new java.awt.Color(204, 204, 204));
        navLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navLogout.setText("Logout");
        navLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navLogoutMouseExited(evt);
            }
        });
        navLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLogoutActionPerformed(evt);
            }
        });

        navPengurus.setBackground(new java.awt.Color(204, 204, 204));
        navPengurus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navPengurus.setText("Pengurus");
        navPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navPengurusActionPerformed(evt);
            }
        });

        navHistory.setBackground(new java.awt.Color(204, 204, 204));
        navHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navHistory.setText("Retur");
        navHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navHistoryActionPerformed(evt);
            }
        });

        navBuku.setBackground(new java.awt.Color(212, 234, 247));
        navBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navBuku.setText("Buku");
        navBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBukuActionPerformed(evt);
            }
        });

        navSirkulasi.setBackground(new java.awt.Color(204, 204, 204));
        navSirkulasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navSirkulasi.setText("Peminjaman");
        navSirkulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navSirkulasiActionPerformed(evt);
            }
        });

        navBeranda.setBackground(new java.awt.Color(204, 204, 204));
        navBeranda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navBeranda.setText("Beranda");
        navBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBerandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(navBeranda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navSirkulasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navPengurus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navLogout)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navLogout)
                    .addComponent(namaUser)
                    .addComponent(navPengurus)
                    .addComponent(navHistory)
                    .addComponent(navBuku)
                    .addComponent(navSirkulasi)
                    .addComponent(navBeranda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cari Buku");

        CariBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TabelDataBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TabelDataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Judul", "Penulis", "Penerbit", "Genre", "ISBN"
            }
        ));
        TabelDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataBuku);
        if (TabelDataBuku.getColumnModel().getColumnCount() > 0) {
            TabelDataBuku.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        searchBy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Judul", "Penulis", "Penerbit", "Genre", "ISBN" }));
        searchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByActionPerformed(evt);
            }
        });

        btnCariBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCariBuku.setText("Cari");
        btnCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBukuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kode");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Judul Buku");

        TampilBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TampilBuku.setText("Tampilkan Buku");
        TampilBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilBukuActionPerformed(evt);
            }
        });

        InputKode.setEditable(false);
        InputKode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        InputJudul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InputJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputJudulActionPerformed(evt);
            }
        });

        InputPenulis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        InputPenerbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        InputGenre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        InputISBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Penulis");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Penerbit");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Genre");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ISBN");

        btnClearForm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClearForm.setText("Clear Form");
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        btnTambahBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTambahBuku.setText("Tambah");
        btnTambahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBukuActionPerformed(evt);
            }
        });

        btnUpdateBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdateBuku.setText("Update");
        btnUpdateBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBukuActionPerformed(evt);
            }
        });

        btnDeleteBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteBuku.setText("Delete");
        btnDeleteBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBukuActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Daftar Buku Perpustakaan Neural Book");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(InputJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(InputPenulis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(InputPenerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(InputGenre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(InputISBN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(btnClearForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUpdateBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(72, 72, 72)
                                .addComponent(InputKode, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TampilBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariBuku)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TampilBuku)
                    .addComponent(jLabel3)
                    .addComponent(InputKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnUpdateBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnDeleteBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(btnClearForm)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseEntered
        // TODO add your handling code here:
        navLogout.setBackground(Color.decode("#d4eaf7"));
    }//GEN-LAST:event_navLogoutMouseEntered

    private void navLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseExited
        // TODO add your handling code here:
        navLogout.setBackground(Color.decode("#cccccc"));
    }//GEN-LAST:event_navLogoutMouseExited

    private void navLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLogoutActionPerformed
        // TODO add your handling code here:
        LoginPage log = new LoginPage();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        DataLogin.clear();
        this.dispose();
        JOptionPane.showMessageDialog(log, "Anda Berhasil Logout");
    }//GEN-LAST:event_navLogoutActionPerformed

    private void navPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navPengurusActionPerformed
        // TODO add your handling code here:
        PengurusPage pengurus = new PengurusPage();
        pengurus.setVisible(true);
        pengurus.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_navPengurusActionPerformed

    private void navHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navHistoryActionPerformed
        // TODO add your handling code here:
        ReturPage history = new ReturPage();
        history.setVisible(true);
        history.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_navHistoryActionPerformed

    private void navBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navBukuActionPerformed

    private void navSirkulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navSirkulasiActionPerformed
        // TODO add your handling code here:
        PeminjamanPage sirkulasi = new PeminjamanPage();
        sirkulasi.setVisible(true);
        sirkulasi.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_navSirkulasiActionPerformed

    private void navBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBerandaActionPerformed
        // TODO add your handling code here:
        BerandaPage beranda = new BerandaPage();
        beranda.setVisible(true);
        beranda.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_navBerandaActionPerformed

    private void InputJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputJudulActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        // TODO add your handling code here:
        InputJudul.setText("");
        InputPenulis.setText("");
        InputPenerbit.setText("");
        InputGenre.setText("");
        InputISBN.setText("");
        InputKode.setText("");
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void TampilBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilBukuActionPerformed
        // TODO add your handling code here:
        bc.isitabel();
    }//GEN-LAST:event_TampilBukuActionPerformed

    private void btnTambahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBukuActionPerformed
        // TODO add your handling code here:
        bc.insert();
        bc.isitabel();
    }//GEN-LAST:event_btnTambahBukuActionPerformed

    private void btnUpdateBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBukuActionPerformed
        // TODO add your handling code here:
        bc.update();
        bc.isitabel();
    }//GEN-LAST:event_btnUpdateBukuActionPerformed

    private void btnDeleteBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBukuActionPerformed
        // TODO add your handling code here:
        bc.delete();
        bc.isitabel();
    }//GEN-LAST:event_btnDeleteBukuActionPerformed

    private void TabelDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataBukuMouseClicked
        // TODO add your handling code here:
        int baris = TabelDataBuku.getSelectedRow();
        InputKode.setText(TabelDataBuku.getValueAt(baris, 0).toString());
        InputJudul.setText(TabelDataBuku.getValueAt(baris, 1).toString());
        InputPenulis.setText(TabelDataBuku.getValueAt(baris, 2).toString());
        InputPenerbit.setText(TabelDataBuku.getValueAt(baris, 3).toString());
        InputGenre.setText(TabelDataBuku.getValueAt(baris, 4).toString());
        InputISBN.setText(TabelDataBuku.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_TabelDataBukuMouseClicked

    private void btnCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBukuActionPerformed
        // TODO add your handling code here:
        bc.search();
    }//GEN-LAST:event_btnCariBukuActionPerformed

    private void searchByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CariBuku;
    private javax.swing.JTextField InputGenre;
    private javax.swing.JTextField InputISBN;
    private javax.swing.JTextField InputJudul;
    private javax.swing.JTextField InputKode;
    private javax.swing.JTextField InputPenerbit;
    private javax.swing.JTextField InputPenulis;
    private javax.swing.JTable TabelDataBuku;
    private javax.swing.JButton TampilBuku;
    private javax.swing.JButton btnCariBuku;
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnDeleteBuku;
    private javax.swing.JButton btnTambahBuku;
    private javax.swing.JButton btnUpdateBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namaUser;
    private javax.swing.JButton navBeranda;
    private javax.swing.JButton navBuku;
    private javax.swing.JButton navHistory;
    private javax.swing.JButton navLogout;
    private javax.swing.JButton navPengurus;
    private javax.swing.JButton navSirkulasi;
    private javax.swing.JComboBox<String> searchBy;
    // End of variables declaration//GEN-END:variables

    public JTextField getInputGenre() {
        return InputGenre;
    }

    public void setInputGenre(JTextField InputGenre) {
        this.InputGenre = InputGenre;
    }

    public JTextField getInputISBN() {
        return InputISBN;
    }

    public void setInputISBN(JTextField InputISBN) {
        this.InputISBN = InputISBN;
    }

    public JTextField getInputJudul() {
        return InputJudul;
    }

    public void setInputJudul(JTextField InputJudul) {
        this.InputJudul = InputJudul;
    }

    public JTextField getInputKode() {
        return InputKode;
    }

    public void setInputKode(JTextField InputKode) {
        this.InputKode = InputKode;
    }

    public JTextField getInputPenerbit() {
        return InputPenerbit;
    }

    public void setInputPenerbit(JTextField InputPenerbit) {
        this.InputPenerbit = InputPenerbit;
    }

    public JTextField getInputPenulis() {
        return InputPenulis;
    }

    public void setInputPenulis(JTextField InputPenulis) {
        this.InputPenulis = InputPenulis;
    }

    public JTable getTabelDataBuku() {
        return TabelDataBuku;
    }

    public void setTabelDataBuku(JTable TabelDataBuku) {
        this.TabelDataBuku = TabelDataBuku;
    }

    public JComboBox<String> getListKolomCari() {
        return searchBy;
    }

    public void setListKolomCari(JComboBox<String> listKolomCari) {
        this.searchBy = listKolomCari;
    }

    public JComboBox<String> getSearchBy() {
        return searchBy;
    }

    public void setSearchBy(JComboBox<String> searchBy) {
        this.searchBy = searchBy;
    }

    public JTextField getCariBuku() {
        return CariBuku;
    }

    public void setCariBuku(JTextField CariBuku) {
        this.CariBuku = CariBuku;
    }

}
