/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.PeminjamanControl;
import Model.DataLogin;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author L E N O V O
 */
public class PeminjamanPage extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    
    PeminjamanControl pc;
    public PeminjamanPage() {
        super("Sistem Manajemen Perpustakaan");
        initComponents();
        pc = new PeminjamanControl(this);
        pc.isitabel();
        namaUser.setText("Welcome, " + DataLogin.getNama_lengkap() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        namaUser = new javax.swing.JLabel();
        navLogout = new javax.swing.JButton();
        navPengurus = new javax.swing.JButton();
        navHistory = new javax.swing.JButton();
        navBuku = new javax.swing.JButton();
        navSirkulasi = new javax.swing.JButton();
        navBeranda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CariBuku = new javax.swing.JTextField();
        searchBy = new javax.swing.JComboBox<>();
        btnCariBuku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataBuku = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        InputKode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelDataPinjam = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 140));

        namaUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namaUser.setForeground(new java.awt.Color(255, 255, 255));
        namaUser.setText("Welcome, Nama Lengkap");

        navLogout.setBackground(new java.awt.Color(204, 204, 204));
        navLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navLogout.setText("Logout");
        navLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navLogoutMouseExited(evt);
            }
        });
        navLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLogoutActionPerformed(evt);
            }
        });

        navPengurus.setBackground(new java.awt.Color(204, 204, 204));
        navPengurus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navPengurus.setText("Pengurus");
        navPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navPengurusActionPerformed(evt);
            }
        });

        navHistory.setBackground(new java.awt.Color(204, 204, 204));
        navHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navHistory.setText("Retur");
        navHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navHistoryActionPerformed(evt);
            }
        });

        navBuku.setBackground(new java.awt.Color(204, 204, 204));
        navBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navBuku.setText("Buku");
        navBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBukuActionPerformed(evt);
            }
        });

        navSirkulasi.setBackground(new java.awt.Color(212, 234, 247));
        navSirkulasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navSirkulasi.setText("Peminjaman");
        navSirkulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navSirkulasiActionPerformed(evt);
            }
        });

        navBeranda.setBackground(new java.awt.Color(204, 204, 204));
        navBeranda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        navBeranda.setText("Beranda");
        navBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBerandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(navBeranda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navSirkulasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navPengurus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navLogout)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navLogout)
                    .addComponent(namaUser)
                    .addComponent(navPengurus)
                    .addComponent(navHistory)
                    .addComponent(navBuku)
                    .addComponent(navSirkulasi)
                    .addComponent(navBeranda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cari Buku");

        CariBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        searchBy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Judul", "Penulis", "Penerbit", "Genre", "ISBN" }));
        searchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByActionPerformed(evt);
            }
        });

        btnCariBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCariBuku.setText("Cari");
        btnCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBukuActionPerformed(evt);
            }
        });

        TabelDataBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TabelDataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Judul", "Penulis", "Penerbit", "Genre", "ISBN"
            }
        ));
        TabelDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataBuku);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Peminjam");

        InputKode.setEditable(false);
        InputKode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Pinjam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TabelDataPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kode Buku", "Nama Lengkap"
            }
        ));
        jScrollPane2.setViewportView(TabelDataPinjam);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Daftar Perpustakaan Neural Book");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("List Peminjaman Perpustakaan Neural Book");

        InputNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputKode)
                            .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariBuku)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 126, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseEntered
        // TODO add your handling code here:
        navLogout.setBackground(Color.decode("#d4eaf7"));
    }//GEN-LAST:event_navLogoutMouseEntered

    private void navLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseExited
        // TODO add your handling code here:
        navLogout.setBackground(Color.decode("#cccccc"));
    }//GEN-LAST:event_navLogoutMouseExited

    private void navLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLogoutActionPerformed
        // TODO add your handling code here:
        LoginPage log = new LoginPage();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        DataLogin.clear();
        this.dispose();
        JOptionPane.showMessageDialog(log, "Anda Berhasil Logout");
    }//GEN-LAST:event_navLogoutActionPerformed

    private void navPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navPengurusActionPerformed
        // TODO add your handling code here:
        PengurusPage pengurus = new PengurusPage();
        pengurus.setVisible(true);
        pengurus.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_navPengurusActionPerformed

    private void navHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navHistoryActionPerformed
        // TODO add your handling code here:
        ReturPage history = new ReturPage();
        history.setVisible(true);
        history.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_navHistoryActionPerformed

    private void navBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBukuActionPerformed
        // TODO add your handling code here:
        BukuPage buku = new BukuPage();
        buku.setVisible(true);
        buku.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_navBukuActionPerformed

    private void navSirkulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navSirkulasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navSirkulasiActionPerformed

    private void navBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBerandaActionPerformed
        // TODO add your handling code here:
        BerandaPage beranda = new BerandaPage();
        beranda.setVisible(true);
        beranda.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_navBerandaActionPerformed

    private void searchByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByActionPerformed

    private void btnCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariBukuActionPerformed

    private void TabelDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataBukuMouseClicked
        // TODO add your handling code here:
        int baris = TabelDataBuku.getSelectedRow();
        InputKode.setText(TabelDataBuku.getValueAt(baris, 0).toString());
    }//GEN-LAST:event_TabelDataBukuMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pc.insert();
        pc.isitabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeminjamanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeminjamanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeminjamanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeminjamanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeminjamanPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CariBuku;
    private javax.swing.JTextField InputKode;
    private javax.swing.JTextField InputNama;
    private javax.swing.JTable TabelDataBuku;
    private javax.swing.JTable TabelDataPinjam;
    private javax.swing.JButton btnCariBuku;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel namaUser;
    private javax.swing.JButton navBeranda;
    private javax.swing.JButton navBuku;
    private javax.swing.JButton navHistory;
    private javax.swing.JButton navLogout;
    private javax.swing.JButton navPengurus;
    private javax.swing.JButton navSirkulasi;
    private javax.swing.JComboBox<String> searchBy;
    // End of variables declaration//GEN-END:variables

    public JTextField getCariBuku() {
        return CariBuku;
    }

    public void setCariBuku(JTextField CariBuku) {
        this.CariBuku = CariBuku;
    }

    public JTextField getInputNama() {
        return InputNama;
    }

    public void setInputNama(JTextField InputNama) {
        this.InputNama = InputNama;
    }

    public JTextField getInputKode() {
        return InputKode;
    }

    public void setInputKode(JTextField InputKode) {
        this.InputKode = InputKode;
    }

    public JTable getTabelDataBuku() {
        return TabelDataBuku;
    }

    public void setTabelDataBuku(JTable TabelDataBuku) {
        this.TabelDataBuku = TabelDataBuku;
    }

    public JTable getTabelDataPinjam() {
        return TabelDataPinjam;
    }

    public void setTabelDataPinjam(JTable TabelDataPinjam) {
        this.TabelDataPinjam = TabelDataPinjam;
    }

    public JButton getBtnCariBuku() {
        return btnCariBuku;
    }

    public void setBtnCariBuku(JButton btnCariBuku) {
        this.btnCariBuku = btnCariBuku;
    }

    public JComboBox<String> getSearchBy() {
        return searchBy;
    }

    public void setSearchBy(JComboBox<String> searchBy) {
        this.searchBy = searchBy;
    }

}
